{% set name = "azure-cli-telemetry" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c0141ddeed1319bcc3179617f74859e5f17477ce676051a4ead1d29c75eb9593

build:
  number: 5
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - applicationinsights >=0.11.1
    - portalocker ==1.2.1
    - setuptools
    - pywin32  # [win]

test:
  imports:
    - azure
    - azure.cli
    - azure.cli.telemetry
    - azure.cli.telemetry.components

about:
  home: https://github.com/Azure/azure-cli
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure CLI Telemetry Package

  doc_url: https://docs.microsoft.com/en-us/cli/azure
  dev_url: https://github.com/Azure/azure-cli

extra:
  recipe-maintainers:
    - dhirschfeld
    - andreyz4k
