{% set name = "azure-cli-telemetry" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d922379cda1b48952be75fb3bd2ac5e7ceecf569492a6088bab77894c624a278

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - applicationinsights >=0.11.1,<0.12
    - portalocker >=1.6,<3

test:
  requires:
    - python {{ python_min }}
  imports:
    - azure
    - azure.cli
    - azure.cli.telemetry
    - azure.cli.telemetry.components

about:
  home: https://github.com/Azure/azure-cli
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure CLI Telemetry Package

  doc_url: https://docs.microsoft.com/en-us/cli/azure
  dev_url: https://github.com/Azure/azure-cli/tree/main/src/azure-cli-telemetry

extra:
  recipe-maintainers:
    - dhirschfeld
    - andreyz4k
